<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE subjects[
	<!ELEMENT subjects (subject+)>
	<!ELEMENT subject (id, name, idStudent, assessment)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT idStudent (#PCDATA)>
	<!ELEMENT assessment (#PCDATA)>
]>
<subjects>
	<subject>
		<id>1</id>
		<name>Предмет 1</name>
		<idStudent>1</idStudent>
		<assessment>5</assessment>
	</subject>
</subjects>